### ISSUE TITLE
I can't see the emoji on Windows 10 in chrome v88.

### ISSUE THREAD

**Issue by vishugosain** [risan/country-flag-emoji-json#6]

**Comment by risan** [comment]
Hi @vishugosain, sorry for the late response. Sadly, Microsoft decided not to interpret emoji flag codes on Windows 10. See: [Flag Emoji - Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/all/flag-emoji/85b163bc-786a-4918-9042-763ccf4b6c05)
